parameters:
    portal:
        tile_sizes:
            tile-square: tile-square
            tile-small: tile-small
            tile-wide: tile-wide
            tile-large: tile-large
        colors:
            white: white
            black: black
            lime: lime
            green: green
            emerald: emerald
            teal: teal
            blue: blue
            cyan: cyan
            cobalt: cobalt
            indigo: indigo
            violet: violet
            pink: pink
            magenta: magenta
            crimson: crimson
            red: red
            orange: orange
            amber: amber
            yellow: yellow
            brown: brown
            olive: olive
            steel: steel
            mauve: mauve
            taupe: taupe
            gray: gray
            dark: dark
            darker: darker
            darkBrown: darkBrown
            darkCrimson: darkCrimson
            darkMagenta: darkMagenta
            darkIndigo: darkIndigo
            darkCyan: darkCyan
            darkCobalt: darkCobalt
            darkTeal: darkTeal
            darkEmerald: darkEmerald
            darkGreen: darkGreen
            darkOrange: darkOrange
            darkRed: darkRed
            darkPink: darkPink
            darkViolet: darkViolet
            darkBlue: darkBlue
            lightBlue: lightBlue
            lightRed: lightRed
            lightGreen: lightGreen
            lighterBlue: lighterBlue
            lightTeal: lightTeal
            lightOlive: lightOlive
            lightOrange: lightOrange
            lightPink: lightPink
            grayDark: grayDark
            grayDarker: grayDarker
            grayLight: grayLight
            grayLighter: grayLighter
        icons:
            mif-microscope: microscope
            mif-stack2: stack2
            mif-stack3: stack3
            mif-lamp: lamp
            mif-injection: injection
            mif-thermometer2: thermometer2
            mif-justice: justice
            mif-user-md: user-md
            mif-stethoscope: stethoscope
            mif-ambulance: ambulance
            mif-medkit: medkit
            mif-paw: paw
            mif-file-pdf: file-pdf
            mif-file-word: file-word
            mif-file-excel: file-excel
            mif-file-powerpoint: file-powerpoint
            mif-file-image: file-image
            mif-file-archive: file-archive
            mif-file-audio: file-audio
            mif-file-movie: file-movie
            mif-file-code: file-code
            mif-visa: visa
            mif-mastercard: mastercard
            mif-discover: discover
            mif-amex: amex
            mif-cc-paypal: cc-paypal
            mif-heartbeat: heartbeat
            mif-venus: venus
            mif-mars: mars
            mif-medium: medium
            mif-directions-bike: directions-bike
            mif-location-city: location-city
            mif-library: library
            mif-calculator2: calculator2
            mif-barbell: barbell
            mif-3d-rotation: 3d-rotation
            mif-alarm: alarm
            mif-alarm-on: alarm-on
            mif-favorite: favorite
            mif-settings-ethernet: settings-ethernet
            mif-settings-power: settings-power
            mif-settings-voice: settings-voice
            mif-shopping-basket: shopping-basket
            mif-contacts-dialer: contacts-dialer
            mif-contacts-mail: contacts-mail
            mif-drafts: drafts
            mif-mail: mail
            mif-brightness-auto: brightness-auto
            mif-multitrack-audio: multitrack-audio
            mif-widgets: widgets
            mif-usb: usb
            mif-money: money
            mif-vertical-align-bottom: vertical-align-bottom
            mif-vertical-align-center: vertical-align-center
            mif-vertical-align-top: vertical-align-top
            mif-file-download: file-download
            mif-file-upload: file-upload
            mif-keyboard-return: keyboard-return
            mif-security: security
            mif-looks: looks
            mif-palette: palette
            mif-layers: layers
            mif-layers-clear: layers-clear
            mif-local-airport: local-airport
            mif-florist: florist
            mif-gas-station: gas-station
            mif-hotel: hotel
            mif-local-service: local-service
            mif-map2: map2
            mif-traff: traff
            mif-apps: apps
            mif-chevron-left: chevron-left
            mif-chevron-right: chevron-right
            mif-expand-less: expand-less
            mif-expand-more: expand-more
            mif-menu: menu
            mif-more-horiz: more-horiz
            mif-more-vert: more-vert
            mif-unfold-less: unfold-less
            mif-unfold-more: unfold-more
            mif-not: not
            mif-drive-eta: drive-eta
            mif-event-available: event-available
            mif-event-busy: event-busy
            mif-folder-special: folder-special
            mif-sd-card: folder-sd-card
            mif-sync-disabled: sync-disabled
            mif-sync-problem: sync-problem
            mif-vpn-lock: vpn-lock
            mif-vpn-publ: vpn-publ
            mif-school: school
            mif-file-binary: file-binary
            mif-mail-read: mail-read
            mif-quote: quote
            mif-home: home
            mif-pencil: pencil
            mif-eyedropper: eyedropper
            mif-paint: paint
            mif-image: image
            mif-images: images
            mif-camera: camera
            mif-headphones: headphones
            mif-music: music
            mif-film: film
            mif-video-camera: video-camera
            mif-dice: dice
            mif-books: books
            mif-file-empty: file-empty
            mif-files-empty: files-empty
            mif-file-text: file-text
            mif-file-picture: file-picture
            mif-file-music: file-music
            mif-file-play: file-play
            mif-file-video: file-video
            mif-file-zip: file-zip
            mif-stack: stack
            mif-folder: folder
            mif-folder-open: folder-open
            mif-folder-plus: folder-plus
            mif-folder-minus: folder-minus
            mif-folder-download: folder-download
            mif-folder-upload: folder-upload
            mif-tag: tag
            mif-tags: tags
            mif-barcode: barcode
            mif-qrcode: qrcode
            mif-cart: cart
            mif-credit-card: credit-card
            mif-calculator: calculator
            mif-help: help
            mif-envelop: envelop
            mif-location: location
            mif-compass: compass
            mif-compass2: compass2
            mif-map: map
            mif-history: history
            mif-bell: bell
            mif-calendar: calendar
            mif-printer: printer
            mif-keyboard: keyboard
            mif-download: download
            mif-upload: upload
            mif-floppy-disk: floppy-disk
            mif-drive: drive
            mif-database: database
            mif-undo: undo
            mif-redo: redo
            mif-bubble: bubble
            mif-bubbles: bubbles
            mif-user: user
            mif-users: users
            mif-user-plus: user-plus
            mif-user-minus: user-minus
            mif-user-check: user-check
            mif-hour-glass: hour-glass
            mif-search: search
            mif-zoom-in: zoom-in
            mif-zoom-out: zoom-out
            mif-enlarge: enlarge
            mif-shrink: shrink
            mif-enlarge2: enlarge2
            mif-shrink2: shrink2
            mif-key: key
            mif-wrench: wrench
            mif-equalizer: equalizer
            mif-equalizer-v: equalizer-v
            mif-cog: cog
            mif-cogs: cogs
            mif-magic-wand: magic-wand
            mif-bug: bug
            mif-trophy: trophy
            mif-gift: gift
            mif-spoon-fork: spoon-fork
            mif-rocket: rocket
            mif-meter: meter
            mif-hammer: hammer
            mif-fire: fire
            mif-lab: lab
            mif-bin: bin
            mif-truck: truck
            mif-target: target
            mif-power: power
            mif-switch: switch
            mif-power-cord: power-cord
            mif-clipboard: clipboard
            mif-list-numbered: list-numbered
            mif-list: list
            mif-list2: list2
            mif-tree: tree
            mif-cloud: cloud
            mif-cloud-download: cloud-download
            mif-cloud-upload: cloud-upload
            mif-download2: download2
            mif-upload2: upload2
            mif-earth: earth
            mif-link: link
            mif-flag: flag
            mif-attachment: attachment
            mif-eye: eye
            mif-bookmark: bookmark
            mif-bookmarks: bookmarks
            mif-contrast: contrast
            mif-brightness: brightness
            mif-star-empty: star-empty
            mif-star-half: star-half
            mif-star-half: star-half
            mif-star-full: star-full
            mif-heart: heart
            mif-heart-broken: heart-broken
            mif-warning: warning
            mif-notification: notification
            mif-question: question
            mif-plus: plus
            mif-minus: minus
            mif-info: info
            mif-cancel: cancel
            mif-blocked: blocked
            mif-cross: cross
            mif-checkmark: checkmark
            mif-spell-check: spell-check
            mif-enter: enter
            mif-exit: exit
            mif-arrow-up-left: arrow-up-left
            mif-arrow-up: arrow-up
            mif-arrow-up-right: arrow-up-right
            mif-arrow-right: arrow-right
            mif-arrow-down-right: arrow-down-right
            mif-arrow-down: arrow-down
            mif-arrow-down-left: arrow-down-left
            mif-arrow-left: arrow-left
            mif-tab: tab
            mif-move-up: move-up
            mif-move-down: move-down
            mif-sort-asc: sort-asc
            mif-sort-desc: sort-desc
            mif-command: command
            mif-shift: shift
            mif-crop: crop
            mif-filter: filter
            mif-bold: bold
            mif-underline: underline
            mif-italic: italic
            mif-strikethrough: strikethrough
            mif-page-break: page-break
            mif-superscript: superscript
            mif-subscript: subscript
            mif-table: table
            mif-insert-template: insert-template
            mif-pilcrow: pilcrow
            mif-ltr: ltr
            mif-rtl: rtl
            mif-section: section
            mif-paragraph-left: paragraph-left
            mif-paragraph-center: paragraph-center
            mif-paragraph-right: paragraph-right
            mif-paragraph-justify: paragraph-justify
            mif-indent-increase: indent-increase
            mif-indent-decrease: indent-decrease
            mif-embed: embed
            mif-embed2: embed2
            mif-share: share
            mif-feed3: feed3
            mif-chevron-thin-down: chevron-thin-down
            mif-chevron-thin-left: chevron-thin-left
            mif-chevron-thin-right: chevron-thin-right
            mif-chevron-thin-up: chevron-thin-up
            mif-flow-branch: flow-branch
            mif-flow-cascade: flow-cascade
            mif-flow-line: flow-line
            mif-flow-parallel: flow-parallel
            mif-flow-tree: flow-tree
            mif-air: air
            mif-medal: medal
            mif-paper-plane: paper-plane
            mif-shareable: shareable
            mif-shop: shop
            mif-shopping-basket2: shopping-basket2
            mif-thumbs-down: thumbs-down
            mif-thumbs-up: thumbs-up
            mif-traffic-cone: traffic-cone
            mif-water: water
            mif-cabinet: cabinet
            mif-suitcase: suitcase
            mif-gamepad: gamepad
            mif-lock: lock
            mif-unlock: unlock
            mif-tools: tools
            mif-pin: pin
            mif-discout: discout
            mif-profile: profile
            mif-dollar: dollar
            mif-dollars: dollars
            mif-coins: coins
            mif-male: male
            mif-female: female
            mif-piano: piano
            mif-anchor: anchor
            mif-wifi-low: wifi-low
            mif-wifi-mid: wifi-mid
            mif-wifi-full: wifi-full
            mif-perm-phone-msg: perm-phone-msg
            mif-bt-settings: bt-settings
            mif-settings-phone: settings-phone
            mif-dialer-sip: dialer-sip
            mif-dialpad: dialpad
            mif-ring-volume: ring-volume
            mif-voicemail: voicemail
            mif-bluetooth: bluetooth
            mif-bt-connected: bt-connected
            mif-bt-disabled: bt-disabled
            mif-bt-searching: bt-searching
            mif-phonelink: phonelink
            mif-phonelink-off: phonelink-off
            mif-my-location: my-location
            mif-bt-audio: bt-audio
            mif-phone-bt: phone-bt
            mif-phone-forwarded: phone-forwarded
            mif-phone-in-talk: phone-in-talk
            mif-phone-locked: phone-locked
            mif-phone-missed: phone-missed
            mif-phone-paused: phone-paused
            mif-headphones: headphones
            mif-wifi-connect: wifi-connect
            mif-feed: feed
            mif-mic: mic
            mif-phone: phone
            mif-satellite: satellite
            mif-battery-full: battery-full
            mif-battery-two: battery-two
            mif-battery-one: battery-one
            mif-battery-empty: battery-empty
            mif-battery-charge: battery-charge
            mif-display: display
            mif-laptop: laptop
            mif-mobile: mobile
            mif-tablet: tablet
            mif-tablet-landscape: tablet-landscape
            mif-play: play
            mif-pause: pause
            mif-stop: stop
            mif-backward: backward
            mif-forward: forward
            mif-first: first
            mif-last: last
            mif-previous: previous
            mif-next: next
            mif-eject: eject
            mif-volume-high: volume-high
            mif-volume-medium: volume-medium
            mif-volume-low: volume-low
            mif-volume-mute: volume-mute
            mif-volume-mute2: volume-mute2
            mif-volume-plus: volume-plus
            mif-volume-minus: volume-minus
            mif-loop: loop
            mif-loop2: loop2
            mif-infinite: infinite
            mif-shuffle: shuffle
            mif-google: google
            mif-google-plus: google-plus
            mif-facebook: facebook
            mif-twitter: twitter
            mif-youtube: youtube
            mif-steam: steam
            mif-onedrive: onedrive
            mif-github: github
            mif-git: git
            mif-apple: apple
            mif-android: android
            mif-windows: windows
            mif-skype: skype
            mif-linkedin: linkedin
            mif-html5: html5
            mif-css3: css3
            mif-chrome: chrome
            mif-firefox: firefox
            mif-ie: ie
            mif-opera: opera
            mif-safari: safari
            mif-creative-cloud: creative-cloud
            mif-dropbox: dropbox
            mif-evernote: evernote
            mif-paypal: paypal
            mif-swarm: swarm
            mif-vk: vk
            mif-yelp: yelp
            mif-dribbble: dribbble
            mif-lastfm: lastfm
            mif-pinterest: pinterest
            mif-stumbleupon: stumbleupon
            mif-vimeo: vimeo
            mif-sunrise: sunrise
            mif-sun: sun
            mif-moon: moon
            mif-windy: windy
            mif-wind: wind
            mif-snowflake: showflake
            mif-cloudy: cloudy
            mif-cloudy2: cloudy2
            mif-cloud2: cloud2
            mif-weather: weather
            mif-weather2: weather2
            mif-weather3: weather3
            mif-lines: lines
            mif-cloud3: cloud3
            mif-lightning: lightning
            mif-lightning2: lightning2
            mif-rainy: rainy
            mif-windy2: windy2
            mif-windy3: windy3
            mif-snowy: snowy
            mif-snowy2: snowy2
            mif-snowy3: snowy3
            mif-weather4: weather4
            mif-cloudy2: cloudy2
            mif-cloud4: cloud4
            mif-lightning3: lightning3
            mif-sun4: sun4
            mif-moon2: moon2
            mif-cloudy3: cloudy3
            mif-cloud5: cloud5
            mif-lightning4: lightning4
            mif-rainy3: rainy3
            mif-windy4: windy4
            mif-windy5: windy5
            mif-snowy4: snowy4
            mif-snowy5: snowy5
            mif-weather5: weather5
            mif-cloudy4: cloudy4
            mif-lightning5: lightning5
            mif-thermometer: thermometer
            mif-none: none
            mif-celsius: celsius
            mif-fahrenheit: fahrenheit
            mif-chart-bars: chart-bars
            mif-chart-bars2: chart-bars2
            mif-chart-dots: chart-dots
            mif-chart-pie: chart-pie
            mif-chart-line: chart-line
            mif-spinner: spinner
            mif-spinner2: spinner2
            mif-spinner3: spinner3
            mif-spinner4: spinner4
            mif-spinner5: spinner5
            mif-loop2: loop2
        effects:
            slideLeft: slideLeft
            slideRight: slideRight
            slideDown: slideDown
            slideUpDown: slideUpDown
            slideLeftRight: slideLeftRight
            slideUp: slideUp