<?php

namespace UCI\Boson\PortalBundle;

use Symfony\Component\HttpKernel\Bundle\Bundle;
use UCI\Boson\PortalBundle\Util\Globals;

class PortalBundle extends Bundle
{
    public function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        Globals::setUploadDir($this->container->getParameter('portal')['upload_dir']);
    }

}
