<?php

namespace UCI\Boson\PortalBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * TileGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContentRepository extends EntityRepository
{
    public function getAll()
    {
        $query = $this->_em->createQueryBuilder()
            ->select('content')
            ->from('PortalBundle:Content', 'content')
            ->getQuery();

        return $query->getArrayResult();
    }

    public function getTilesByContent($id)
    {
        $query = $this->_em->createQueryBuilder();
        $query->select('tile')
            ->from('PortalBundle:Tile', 'tile')
            ->join('tile.contents', 'content')
            ->where("content.id = $id");

        return $query->getQuery()->getResult();

    }
}
