tile:
    path:     /
    defaults: { _controller: "PortalBundle:Tile:index" }

tile_show:
    path:     /{id}/show
    defaults: { _controller: "PortalBundle:Tile:show" }

tile_new:
    path:     /new
    defaults: { _controller: "PortalBundle:Tile:new" }

tile_create:
    path:     /create
    defaults: { _controller: "PortalBundle:Tile:create" }
    requirements: { _method: post }

tile_edit:
    path:     /{id}/edit
    defaults: { _controller: "PortalBundle:Tile:edit" }

tile_update:
    path:     /{id}/update
    defaults: { _controller: "PortalBundle:Tile:update" }
    requirements: { _method: post|put }

tile_delete:
    path:     /{id}/delete
    defaults: { _controller: "PortalBundle:Tile:delete" }
    requirements: { _method: post|delete }